import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          ShopView(),
        ]),
      ),
    );
  }
}

class ShopView extends StatelessWidget {
  const ShopView({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 912,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFFF3F3F3),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(28),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 33,
                top: 209,
                child: SizedBox(
                  width: 327,
                  height: 101,
                  child: Stack(
                    children: [
                      const Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 327,
                          height: 32,
                          child: Text(
                            'The Shop',
                            style: TextStyle(
                              color: Color(0xFF4A4646),
                              fontSize: 40,
                              fontFamily: 'Karla',
                              fontWeight: FontWeight.w700,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 0,
                        top: 58,
                        child: SizedBox(
                          width: 288,
                          height: 43,
                          child: Text(
                            'Spend your hard-earned points for goodies!',
                            style: TextStyle(
                              color: Color(0xFF4A4646),
                              fontSize: 20,
                              fontFamily: 'Karla',
                              fontWeight: FontWeight.w300,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 187,
                        top: 0,
                        child: Container(
                          width: 50,
                          height: 50,
                          decoration: const BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage(
                                  "https://via.placeholder.com/50x50"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 33,
                top: 352,
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    SizedBox(
                      width: 327,
                      height: 214,
                      child: Stack(
                        children: [
                          Positioned(
                            left: 0,
                            top: 0,
                            child: Container(
                              width: 327,
                              height: 214,
                              padding: const EdgeInsets.only(
                                top: 52,
                                left: 18,
                                right: 18,
                                bottom: 24,
                              ),
                              decoration: ShapeDecoration(
                                color: const Color(0xFFECECEB),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(15),
                                ),
                                shadows: const [
                                  BoxShadow(
                                    color: Color(0x3F000000),
                                    blurRadius: 4,
                                    offset: Offset(0, 4),
                                    spreadRadius: 0,
                                  )
                                ],
                              ),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  const SizedBox(
                                    width: 236,
                                    child: Text(
                                      '“Give my Task to someone else”',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF4A4646),
                                        fontSize: 24,
                                        fontFamily: 'Karla',
                                        fontWeight: FontWeight.w400,
                                        height: 0,
                                      ),
                                    ),
                                  ),
                                  const SizedBox(height: 22),
                                  SizedBox(
                                    width: 161,
                                    height: 60,
                                    child: Stack(
                                      children: [
                                        Positioned(
                                          left: 0,
                                          top: 5,
                                          child: Container(
                                            width: 161,
                                            height: 50,
                                            decoration: ShapeDecoration(
                                              color: const Color(0xFF807D7D),
                                              shape: RoundedRectangleBorder(
                                                  borderRadius:
                                                      BorderRadius.circular(8)),
                                              shadows: const [
                                                BoxShadow(
                                                  color: Color(0x3F000000),
                                                  blurRadius: 4,
                                                  offset: Offset(0, 4),
                                                  spreadRadius: 0,
                                                )
                                              ],
                                            ),
                                          ),
                                        ),
                                        const Positioned(
                                          left: 0,
                                          top: 0,
                                          child: SizedBox(
                                            width: 161,
                                            height: 60,
                                            child: Text(
                                              'Buy for 1000pts',
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                color: Color(0xFFF5F5F5),
                                                fontSize: 15,
                                                fontFamily: 'Karla',
                                                fontWeight: FontWeight.w800,
                                                height: 0,
                                              ),
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                          const Positioned(
                            left: 12,
                            top: 14,
                            child: SizedBox(
                              width: 263.36,
                              height: 24.60,
                              child: Text(
                                'Recommended for you',
                                style: TextStyle(
                                  color: Color(0xFFB4B4B4),
                                  fontSize: 14,
                                  fontFamily: 'Karla',
                                  fontWeight: FontWeight.w700,
                                  height: 0,
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(width: 23),
                    Container(
                      width: 152,
                      padding: const EdgeInsets.only(
                        top: 52,
                        left: 18,
                        right: 18,
                        bottom: 13,
                      ),
                      decoration: ShapeDecoration(
                        color: const Color(0xFFECECEB),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(15),
                        ),
                        shadows: const [
                          BoxShadow(
                            color: Color(0x3F000000),
                            blurRadius: 4,
                            offset: Offset(0, 4),
                            spreadRadius: 0,
                          )
                        ],
                      ),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          const SizedBox(
                            width: 133,
                            child: Text(
                              'Item 2',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF4A4646),
                                fontSize: 20,
                                fontFamily: 'Karla',
                                fontWeight: FontWeight.w400,
                                height: 0,
                              ),
                            ),
                          ),
                          const SizedBox(height: 22),
                          SizedBox(
                            width: 117,
                            height: 60,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0,
                                  top: 5,
                                  child: Container(
                                    width: 117,
                                    height: 50,
                                    decoration: ShapeDecoration(
                                      color: const Color(0xFFF3F3F3),
                                      shape: RoundedRectangleBorder(
                                          borderRadius:
                                              BorderRadius.circular(8)),
                                      shadows: const [
                                        BoxShadow(
                                          color: Color(0x3F000000),
                                          blurRadius: 4,
                                          offset: Offset(0, 4),
                                          spreadRadius: 0,
                                        )
                                      ],
                                    ),
                                  ),
                                ),
                                const Positioned(
                                  left: 30.75,
                                  top: 0,
                                  child: SizedBox(
                                    width: 55.50,
                                    height: 60,
                                    child: Text(
                                      '500pts',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF807D7D),
                                        fontSize: 15,
                                        fontFamily: 'Karla',
                                        fontWeight: FontWeight.w800,
                                        height: 0,
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(width: 23),
                    const SizedBox(
                      width: 323,
                      height: 57.92,
                      child: Stack(
                        children: [
                          Positioned(
                            left: 301,
                            top: 0,
                            child: Text(
                              '+',
                              style: TextStyle(
                                color: Color(0xFFB4B4B4),
                                fontSize: 40,
                                fontFamily: 'Karla',
                                fontWeight: FontWeight.w700,
                                height: 0,
                              ),
                            ),
                          ),
                          Positioned(
                            left: 0,
                            top: 16,
                            child: SizedBox(
                              width: 197,
                              height: 41.92,
                              child: Text(
                                'Household Shop',
                                style: TextStyle(
                                  color: Color(0xFF4A4646),
                                  fontSize: 24,
                                  fontFamily: 'Karla',
                                  fontWeight: FontWeight.w700,
                                  height: 0,
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(width: 23),
                    Container(
                      width: 152,
                      padding: const EdgeInsets.only(
                        top: 52,
                        left: 18,
                        right: 18,
                        bottom: 13,
                      ),
                      decoration: ShapeDecoration(
                        color: const Color(0xFFECECEB),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(15),
                        ),
                        shadows: const [
                          BoxShadow(
                            color: Color(0x3F000000),
                            blurRadius: 4,
                            offset: Offset(0, 4),
                            spreadRadius: 0,
                          )
                        ],
                      ),
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.center,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          const SizedBox(
                            width: 133,
                            child: Text(
                              'Item 3',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFF4A4646),
                                fontSize: 20,
                                fontFamily: 'Karla',
                                fontWeight: FontWeight.w400,
                                height: 0,
                              ),
                            ),
                          ),
                          const SizedBox(height: 22),
                          SizedBox(
                            width: 117,
                            height: 60,
                            child: Stack(
                              children: [
                                Positioned(
                                  left: 0,
                                  top: 5,
                                  child: Container(
                                    width: 117,
                                    height: 50,
                                    decoration: ShapeDecoration(
                                      color: const Color(0xFFF3F3F3),
                                      shape: RoundedRectangleBorder(
                                          borderRadius:
                                              BorderRadius.circular(8)),
                                      shadows: const [
                                        BoxShadow(
                                          color: Color(0x3F000000),
                                          blurRadius: 4,
                                          offset: Offset(0, 4),
                                          spreadRadius: 0,
                                        )
                                      ],
                                    ),
                                  ),
                                ),
                                const Positioned(
                                  left: 30.75,
                                  top: 0,
                                  child: SizedBox(
                                    width: 55.50,
                                    height: 60,
                                    child: Text(
                                      '500pts',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Color(0xFF807D7D),
                                        fontSize: 15,
                                        fontFamily: 'Karla',
                                        fontWeight: FontWeight.w800,
                                        height: 0,
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              Positioned(
                left: -52,
                top: -77,
                child: Container(
                  width: 496,
                  height: 258,
                  decoration: const BoxDecoration(color: Color(0xFFF3F3F3)),
                ),
              ),
              Positioned(
                left: 124,
                top: 83,
                child: SizedBox(
                  width: 144,
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 27, vertical: 9),
                        decoration: ShapeDecoration(
                          color: const Color(0xFFEDECEC),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(10),
                          ),
                        ),
                        child: const Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              '1150 pts',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFFB4B4B4),
                                fontSize: 24,
                                fontFamily: 'Karla',
                                fontWeight: FontWeight.w700,
                                height: 0,
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 17),
                      Container(
                        padding: const EdgeInsets.symmetric(
                            horizontal: 27, vertical: 9),
                        decoration: ShapeDecoration(
                          color: const Color(0xFFEDECEC),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(10),
                          ),
                        ),
                        child: const Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Text(
                              'lvl 25',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Color(0xFFB4B4B4),
                                fontSize: 24,
                                fontFamily: 'Karla',
                                fontWeight: FontWeight.w700,
                                height: 0,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 304,
                top: 25,
                child: SizedBox(
                  height: 16,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 13,
                        child: Transform(
                          transform: Matrix4.identity()
                            ..translate(0.0, 0.0)
                            ..rotateZ(-1.57),
                          child: Container(
                            width: 11,
                            height: 22,
                            decoration: const ShapeDecoration(
                              color: Color(0xB2D9D9D9),
                              shape: StarBorder.polygon(sides: 3),
                            ),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 23,
                        top: 0,
                        child: Text(
                          'back',
                          style: TextStyle(
                            color: Color(0xFFD9D9D9),
                            fontSize: 14,
                            fontFamily: 'Karla',
                            fontWeight: FontWeight.w700,
                            height: 0,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
